apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "shopware-chart.fullname" . }}-custom-config"
  labels: {{- include "shopware-chart.labels" . | nindent 4 }}
data:
  custom.yml: {{ .Values.shopware.customConfig | quote }}