apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopware-chart.fullname" . }}
  labels:
    {{- include "shopware-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "shopware-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "shopware-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: state-pvc
          persistentVolumeClaim:
            claimName: "{{ include "shopware-chart.fullname" . }}-state"
        - name: custom-config
          configMap:
            name: "{{ include "shopware-chart.fullname" . }}-custom-config"
        - name: jwt
          secret:
            secretName: "{{ include "shopware-chart.fullname" . }}-jwt"
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["maintenance"]
          envFrom:
            - secretRef:
                name: "{{ include "shopware-chart.fullname" . }}-env"
          volumeMounts:
            - name: state-pvc
              mountPath: /state
              subPath: ./state
            - name: custom-config
              mountPath: "/var/www/html/config/packages/custom.yaml"
              subPath: ./custom.yml
              readOnly: true
            - name: jwt
              mountPath: "/var/www/html/config/jwt/"
              readOnly: true
          env:
            {{- include "shopware-chart.env-cfg" . | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["web"]
          envFrom:
            - secretRef:
                name: "{{ include "shopware-chart.fullname" . }}-env"
          env:
            {{- include "shopware-chart.env-cfg" . | nindent 12 }}
          volumeMounts:
            - name: custom-config
              mountPath: "/var/www/html/config/packages/custom.yaml"
              subPath: ./custom.yml
              readOnly: true
            - name: jwt
              mountPath: "/var/www/html/config/jwt/"
              readOnly: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
