apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "shopware-chart.fullname" . }}-jwt"
  labels: {{- include "shopware-chart.labels" . | nindent 4 }}
type: Opaque
data:
  public.pem: "{{ b64enc (.Files.Get "jwt_public.pem" ) }}"
  private.pem: "{{ b64enc (.Files.Get "jwt_private.pem") }}"