apiVersion: v1
data:
    public.pem: ENC[AES256_GCM,data:GUSswn3HCa9tbTJl2HwTWQ94ugzLrE8K2C2oQ/4dn4NJHr33DZ1POKlcNB4eHSp3yOiH+704C/nfnSskk9fFfqR+fECdYJ/V6LTp0PY2IWQF/VAR23zk75YSFEZ2bHx9mI1vbJM/v8/I6OrUSZNoxuzdRV7sZBupFz1AVQJWUi6r4ZFFcUvqJpXjplTqwjGmXr3N7Lw8eGM07kxHAiw0Mm0INzhySE2bPNotWoNvrRo+oK2vMXLTQmxsCjuoiFfA60EOn1mA1fkbnZsrloa+d7FRrVuaJGWQwCDav205Kn4eEPCCdhQk50Y+IH/Cyww8Zp+4OuoAo+H1vof71ow7k/T87NZdwUeqDF0uNcy1wHnrjbkAj/xZf+7l5K4eVPBgcEC8vrBMgQEaJKscokLX/6vRsktyGrw+6bCbD6SpCBbOsgNG795hb3A47+jK5qafN7fpxT6F+vUVw1txiH8E8XOx5m/2BPf3FifAzXk7V+n+zin/duFHGA3alFbxRurHQK6XkV78IPzHFvdGpf9HMpox2Kz1QzfmUoWrgoOj5j+Vxlcx6IPWkl1PyNTIhRyZtY7mq7t0DAqmiJr+qhY8qnWoz4W3Ur0IYQPfya3Qwu+hny50/k/IuxAhSA7JQXh1FLpW4VgsKNoNlSfBRO0Cu8O+Il2tQobVDASapvdHo67BwK4+Xjv54qozaJeY2dVS2wdaiy3a+xKyD1oDIo9joIMviwckz+ZoDIDgEpyON/OcR6ZJu7MV7rAyHNcoG1eyF/XjqhiHTkVDeIczW6BFCJLBe1lXZ0S99Qfs4oXenN29mXdUAww5fsq/i/+4hOBpYJycK05uYw85tRnex0iZiiFpMd/VDfLoB5LOh6dlBpPi4SZ3zx/HYez0Ky+v5uxsWeTBT+r29aHBHyCv9qfthtZKu2lq9DnoeIr8mUbhgr7H5168qozLXF6xijhNTa7kcqkrP570WphTrAIP4/eGNhMgRsKp8QRwc5B50xLMFkVUZQv280e200gVMdrowN2MqJ76hpLUos12zlu8SW9s2II6zZFb78fmieQf/ZzVVQAV103ri5ZS4kQTwqzvB+FgTsBTBMRxEv8JkbDbW2ITmdmIIe+z0DzyKvJ9k1HTl5ObrhbhIBeCU1S05Fs=,iv:V2XEC+Vm4qmyBqLWE3pbQgy10+gGbcRYFdCOA+FdPhU=,tag:pa19v8krHuHDSvpDZxhQqQ==,type:str]
    private.pem: ENC[AES256_GCM,data:w8XqVKlZtGhVX45WiaN1Oo93o5OCvnu3r3KWhlsg4zWOJw2XkqhTXDAM4k+T/oDYmH/ZJsjW40XEK0b+4Sqr/6yXVdZn2eFiQ2aRgAcRkuL5hPBbf3xBdRcqjkajBBf7t14WGO7qm53YHayL6K2n7wazQ7FRnD33t9RhpeBGi8hhMpOokqV9syrCjHBni7ROTVWgP6J5/AxLGTQkg71YkxFE7SAZsKtNii8rkJxW/jgNF7Pllte61Mvyntc0p6Yavbuf/La8V1IJjgIA4H7th4oHMIovEhwNP54ZmRr/bcR7cA+0Q2AuoFshf5DpJDE9oJ8F7A==,iv:mFWGcYEwTXZdKTugYR86HmA9MOs1EWzcU3gPnnUi4Ok=,tag:eiI1b1b1WiRJz1YV1N0e5A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: shopware-jwt
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-19T20:59:42Z'
    mac: ENC[AES256_GCM,data:OhrNyCiiSxHGfH5VT3ix43I0hNnPqjks4RyhCA9titQSPd/djnTCFaa+kp92R33/XbwY7j4dnp5KC55X4wGgKdqRJrAhb+pKa5kgjPm34vaGrczgbBgi0Os8QoIkak+G/rjTHhb7N0GPOuEP3TLQCTOl79NKqt+Gl111NBrLg/8=,iv:l3gQ0Id/z4iES990HU25cx/Hfz247QXwk/0U7YWzejU=,tag:23j2P6VUWsVZ5S+2THlNyw==,type:str]
    pgp:
    -   created_at: '2020-11-19T20:59:42Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA62C02FlycUjAQv/TCvEtbHzlTeMpHhUTPz3rV/sZHQNXO8HdXjZlW4K7KiG
            XHoax0xD7NM5dcWF6Qn5BAcQvDrWs0fuC6gjVNmIB9TwhthhsUmpl8EW9Pi3AT1X
            9bmJ2kflo67k3WBI+5PsxE6C0IKz1HCxX9OCWchA9U+7f76YWbsUVKddWl2BFUb4
            FzTCZO41lSprbN3aXEx7j1d5uGnAP14/4NoPNCqHCHmet+TSUAWStaasr/wBvWTG
            Ll/KIK0IoxHSUB5YLHaCU0Sava260zPxmgPWdL92FMsrqgm3ZewSeYnBdGla/UQR
            wfH1x9ax0uBG9NPCmJqQ/mywP8/rMcDHbz7jeGVVX+AC7MremojQpXUeRqfgYd75
            GF7Zu7V1WYcFcdBA6aJquP35T3DL5RGXYkV8ajlktghyXZgZ9ZXRhDZfQjUOGCbY
            6IdQ6adLSVJEotso6ldURNGJJgi8/sJXhuzTCg0feBVCDOw3NTGzz5hHeCN+Rlm6
            46GrR6B3nLJWx4r8hdnA0l4BAhhiZKs/7h/qV0+S3q/032SFxzm4fbqR04IfCg2k
            UMYEKVgOdjphTkiSwuoMkh8mZHo5Fewaxp6Irgvcq2e0CfWXp+YG82hA0CoV6DKI
            JreGjCVRW/m+7Z08cxJ5
            =mJ61
            -----END PGP MESSAGE-----
        fp: 54DF48CD4E730D6AE88BD18E799958FF47056348
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
