apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "shopware-chart.fullname" . }}-env"
  labels: {{- include "shopware-chart.labels" . | nindent 4 }}
type: Opaque
data:
  INSTANCE_ID: "{{ b64enc (include "shopware-chart.instanceId" .) }}"
  APP_SECRET: "{{ b64enc (include "shopware-chart.appSecret" .) }}"
  DATABASE_URL: "{{ b64enc (.Values.shopware.databaseUrl) }}"
  MAILER_URL: "{{ b64enc (.Values.shopware.mailerUrl) }}"