apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "shopware-chart.fullname" . }}-task-runner"
  labels:
    {{- include "shopware-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.shopware.scheduledTask.enabled }}
  replicas: {{ .Values.shopware.scheduledTask.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "shopware-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "shopware-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      volumes:
        - name: custom-config
          configMap:
            name: "{{ include "shopware-chart.fullname" . }}-custom-config"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["cli", "scheduled-task:run", "--memory-limit=1G", "--time-limit=60"]
          envFrom:
            - secretRef:
                name: "{{ include "shopware-chart.fullname" . }}-env"
          env:
            {{- include "shopware-chart.env-cfg" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: custom-config
              mountPath: "/var/www/html/config/packages/custom.yaml"
              subPath: ./custom.yml
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
